name: Testing Workflow

# Set the branch or branches you want to run this workflow
on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    name: Lint Check

    runs-on: ubuntu-latest

    # Check the code with Android Lint
    # If you use kotlin use ktlint
    steps:
      - name: Clone repo
        uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Decode google services configuration file
      - name: Decode google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > app/google-services.json

      # Lint to flow debug
      - name: Lint debug flavor
        run: ./gradlew lintDebug --stacktrace

      # Lint results
      - name: Lint results
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/reports/lint-results-debug.html

  testing:
    name: Testing

    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Decode google services configuration file
      - name: Decode google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > app/google-services.json

      # Run unit tests
      - name: Run unit tests
        run: ./gradlew test --stacktrace

      # Assemble debug apk to send to firebase test lab
      - name: Assemble debug APK
        run: ./gradlew assembleDebug --stacktrace

      # Assemble debug test apk to send to firebase test lab
      - name: Assemble debug test APK
        run: ./gradlew assembleDebugAndroidTest --stacktrace

      # Run instrumented tests on firebase test lab
      - name: Run instrumented tests on firebase test lab
        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
        with:
          arg-spec: 'tests.yml:android-pixel-4'
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}